stages:
  - test

test:
  image: circleci/node:lts-browsers
  stage: test
  script:
    - yarn install
    - yarn global add firebase-tools
    - yarn run setup:emu:firestore
    - yarn run emu:start:firestore &
    - sleep 3
    - yarn run ci-test
