stages:
  - test

test:
  image: node:8-slim
  stage: test
  script:
    - apt-get update -y
    - apt-get install -y default-jdk
    - yarn install
    - yarn global add firebase-tools
    - firebase setup:emulators:firestore
    - yarn run emu:start:firestore &
    - sleep 3
    - yarn run ci-test

