version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: apt-get update -y
            - run: apt-get install -y default-jdk
            - run: yarn install
            - run: yarn global add firebase-tools
            - run: yarn run setup:emu:firestore
            - run: yarn run emu:start:firestore & sleep 5 & yarn run ci-test
workflows:
  test:
    jobs:
      - test