version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:lts-browsers
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn global add firebase-tools
            - run: yarn run setup:emu:firestore
            - run: yarn run emu:start:firestore & sleep 5 & yarn run ci-test
workflows:
  test:
    jobs:
      - test